Document: cypher-shell
Title: Debian cypher-shell Manual
Author: <insert document author here>
Abstract: This manual describes what cypher-shell is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cypher-shell/cypher-shell.sgml.gz

Format: postscript
Files: /usr/share/doc/cypher-shell/cypher-shell.ps.gz

Format: text
Files: /usr/share/doc/cypher-shell/cypher-shell.text.gz

Format: HTML
Index: /usr/share/doc/cypher-shell/html/index.html
Files: /usr/share/doc/cypher-shell/html/*.html
